version: '2'

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  pgdata:
    driver: local
  static:
    driver: local

services:
  caddy:
    image: zzrot/alpine-caddy #whatever4711/rpi-caddy
    ports:
      - "80:80"
    networks:
      - internal
      - external


  nextcloud:
    build: .
    image: whatever4711/nextcloud:amd64
    depends_on:
      - db
      - redis
    expose:
      - 9000
    networks:
      - internal
    environment:
      - DB_TYPE=pgsql
      - DB_NAME=nextcloud
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    entrypoint: run.sh


  db:
    image: whatever4711/postgres:amd64
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - internal

  redis:
    image: redis #armhf/redis
    #volumes:
    #  - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - internal

  memcache:
    image: memcached:alpine #armhf/memcached:alpine
    entrypoint: memcached -m 64
    networks:
      - internal
