version: '2'

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  pgdata:
    driver: local
  static:
    driver: local
  nextcloud:
    driver: local

services:
  caddy:
    image: whatever4711/caddy:armhf
    depends_on:
      - nextcloud
    ports:
      - "80:80"
    volumes:
      - ./config/Caddyfile:/root/.caddy/Caddyfile
      - nextcloud:/nextcloud
    networks:
      - internal
      - external
    command: --agree --conf /root/.caddy/Caddyfile


  nextcloud:
    build:
      context: ./daily
      dockerfile: Dockerfile.armhf
    image: whatever4711/nextcloud:armhf
    depends_on:
      - db
      - redis
    expose:
      - 9000
    networks:
      - internal
    volumes:
      - nextcloud:/nextcloud
    environment:
      - DB_TYPE=pgsql
      - DB_NAME=nextcloud
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    entrypoint: run.sh


  db:
    image: whatever4711/postgres:armhf
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - internal

  redis:
    image: armhf/redis
    networks:
      - internal

  memcache:
    image: armhf/memcached:alpine
    entrypoint: memcached -m 64
    networks:
      - internal
