version: '3'

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  pg_data:
    driver: local
  nc_config:
    driver: local
  nc_data:
    driver: local
  nc_apps:
    driver: local
  nc_www:
    driver: local

services:
  caddy:
    image: whatever4711/caddy:armhf
    depends_on:
      - nextcloud
    ports:
      - "80:80"
    volumes:
      - ./config/Caddyfile:/root/.caddy/Caddyfile
      - nc_www:/nextcloud
    networks:
      - internal
      - external
    command: --agree --conf /root/.caddy/Caddyfile


  nextcloud:
    build:
      context: ./daily
      dockerfile: Dockerfile.armhf
    image: whatever4711/nextcloud:armhf
    depends_on:
      - postgres
      - redis
      - memcache
    expose:
      - 9000
    networks:
      - internal
    volumes:
      - nc_www:/nextcloud
      - nc_config:/config
      - nc_data:/data
      - nc_apps:/apps
    environment:
      - DB_TYPE=pgsql
      - DB_NAME=nextcloud
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    entrypoint: ["dockerize", "-wait", "tcp://postgres:5432", "-wait", "tcp://redis:6379", "-wait", "tcp://memcache:11211", "run.sh"]


  postgres:
    image: whatever4711/postgres:armhf
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - internal

  redis:
    image: armhf/redis
    volumes:
      - ./config/redis.conf:/redis.conf
    networks:
      - internal
    command:
      - redis-server
      - /redis.conf
    expose:
      - 6379

  memcache:
    image: armhf/memcached:alpine
    networks:
      - internal
    command:
      - -m 64
    expose:
      - 11211
