version: '3.0'
networks:
  tor:

services:
  proxy:
    image: osminogin/tor-simple
    expose:
      - 9050
    networks:
      - tor

  gridseed:
    image: whatever4711/miner:gridseed
    privileged: true
    build:
      context: .
      dockerfile: Gridseed
    networks:
      - tor
    entrypoint: ./start.sh
    command: -b stratum+tcp://eu.multipool.us:3360
#    command: --freq=800 --algo=scrypt -G /dev/ttyACM0 -o stratum+tcp://ltc.pool.minergate.com:3336 -u whatever4711@gmail.com -p x --proxy="socks5://proxy:9050"
#    command: -D --socks-proxy="socks://proxy:9050" --scrypt -o stratum+tcp://ltc.pool.minergate.com:3336 -u whatever4711@gmail.com -p x 
      #--gridseed-options=baud=115200,freq=250,usefifo=0
